### model
model_name_or_path: "magma"
vision_name_or_path: "openai/clip-vit-large-patch14-336"
text_name_or_path: "Qwen/Qwen3-1.7B"
projector_type: "mlp"
new_special_tokens: "<|vision_start|>, <|vision_end|>"
image_token: "<|image|>"

### method
stage: pret
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: false
freeze_language_model: true
deepspeed: scripts/deepspeed/zero3.json

### dataset
# dataset: ocr-vqa-200k
dataset:  demo
template: magma
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 80

### output
output_dir: output/magama/test
logging_steps: 100
save_steps: 20000
overwrite_output_dir: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
